name: Sleep for 10 Minutes

on:
  workflow_dispatch:

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 10 minutes
        run: |
          echo "Sleeping for 10 minutes..."
          sleep 600
          echo "Done sleeping!"
